### ISSUE TITLE
Wan to change the below bug of card title

### ISSUE THREAD

**Issue by grraghav120** [auxfuse/hackathon-git-labs#120] opened 2022-10-08 08:06 UTC
![image](https://user-images.githubusercontent.com/96789493/194697130-b3db59de-d0a8-4422-8ea7-bf4d3584525d.png)
![image](https://user-images.githubusercontent.com/96789493/194697338-408d9e50-65ae-40ac-9cc6-1f3271d3419c.png)

The card title heading getting out of card space .
I want to change this bug
Please assign me under hacktoberfest-accepted

**Comment by auxfuse** [comment] 2022-10-08 14:50
That is not a bug 😄 that is physically on purpose to prove that you can still create modern layouts without the need to stay inside container boundaries 😛 

Thanks anyway. We are going to close this Issue as it does not add any supporting value to the project. 🤜

**Closed by auxfuse** 2022-10-08 14:50 UTC
